from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

urlpatterns = patterns('doit.views',
    url(r'^templates/viewTable', 'viewTable_template'),
    url(r'^(?P<dbname>\w+)/$', 'source_index', name='source_index'),
    url(r'^(?P<dbname>\w+)/lowscorers/$', 'lowscoremapper', name='lowscoremapper'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/map$', 'mapper', name='map_source'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/meta', 'source_meta', name='source_meta'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/data', 'source_data', name='source_data'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/table', 'source_table', name='source_table'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/entities', 'source_entities', name='source_entities'),
    url(r'^(?P<dbname>\w+)/sources/(?P<sid>\d+)/process/(?P<method_index>[0-4])/', 'source_processor', name='source_processor'),
    url(r'^(?P<dbname>\w+)/fields/map$', 'mapper_by_field_set', name='mapper_by_field_set'),
    url(r'^(?P<dbname>\w+)/fields/(?P<comp_op>(like|named))/(?P<field_name>\w+)/map$', 'mapper_by_field_name', name='mapper_by_field_name'),
    url(r'^(?P<dbname>\w+)/save$', 'mapper_results', name='mapper_results'),
    url(r'^(?P<dbname>\w+)/suggest-new-attribute/$', 'suggest_new_attribute', name='suggest_new_attribute'),
    url(r'^(?P<dbname>\w+)/suggest-new-attribute/form', 'suggest_new_attribute_form', name='suggest_new_attribute_form'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/$', redirect_to, {'url': 'summary', }, name='field_index'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/candidates/$', 'field_candidates', name='field_candidates'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/summary$', 'detail_summary', name='detail_summary'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/values/$', redirect_to, {'url': 'examples', }, name='field_values'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/values/examples$', 'detail_examples', name='detail_examples'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/values/shared$', 'detail_shared', name='detail_shared'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/values/distro$', 'detail_distro', name='detail_distro'),
    url(r'^(?P<dbname>\w+)/fields/(?P<fid>\d+)/scores$', 'detail_scoring', name='detail_scoring'),
    url(r'^(?P<dbname>\w+)/entities/compare', 'compare_entities', name='compare_entities'),
)
